services:
  - type: web
    name: marcelo-hernandes-site-pessoal
    runtime: static
    buildCommand: ""
    startCommand: ""
    envVars:
      - key: NODE_ENV
        value: production
    healthCheckPath: /
    autoDeploy: true
    branch: main
    repo: https://github.com/marcelohs402015/site-pessoal
